---

- name: instala chave do PGDG
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    id: "0x7FCC7D46ACCC4CF8"
  state: present

- name: register APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: pgdg

- name: instala postgres (cliente)
  apt:
    name: postgresql-client
    state: latest
  when: "postgres_common_client|bool"

